Repository TEAM-HI25/nonamarket, pull requests merged in 2022-12, with the labels that each got.

#1 <docs> : 회의록 파일 추가
  회의록.md
Labels: docs

#2 <docs> : 코드컨벤션추가
  코드컨벤션.md
Labels: docs

#3 <docs> : PR_template 파일 추가
  PULL_REQUEST_TEMPLATE.md
Labels: docs

#5 <feat> : page Route 작업
  package-lock.json
  package.json
  src/App.js
  src/App.jsx
  src/Router/Router.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/ChatList/ChatList.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/FollowerList/FollowerList.jsx
  src/pages/FollowingList/FollowingList.jsx
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/JoinEmail/JoinEmail.jsx
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
  src/pages/Login/Login.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/ModifyProfile/ModifyProfile.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/SearchUser/SearchUser.jsx
  src/pages/Splash/Splash.jsx
  src/pages/UploadPost/UploadPost.jsx
  src/pages/YourProfile/YourProfile.jsx
Labels: feat

#7 <docs> : 글로벌스타일컴포넌트 생성
  src/styles/Globalstyled.jsx
Labels: docs

#9 <feat> : 버튼 컴포넌트 생성
  src/components/common/Button/Button.jsx
  src/components/common/Button/StyledBtn.jsx
  src/pages/Login/Login.jsx
  src/styles/Globalstyled.jsx
Labels: feat

#19 <feat> : 로그인 선택 페이지 UI 구현
  src/pages/Login/Login.jsx
  src/pages/Login/StyledLogin.jsx
  src/pages/Splash/Splash.jsx
Labels: feat

#20 <feat> : Nav 컴포넌트 생성
  src/components/Nav/ChatNav.jsx
  src/components/Nav/HomeNav.jsx
  src/components/Nav/MainNav.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/SearchNav.jsx
  src/components/Nav/StyledNav.jsx
  src/components/Nav/UploadNav.jsx
Labels: feat

#24 <style> : Nav component 이미지 경로 수정
  src/components/Nav/ChatNav.jsx
  src/components/Nav/HomeNav.jsx
Labels: style

#30 <refact> : 홈피드UI 네브바, 탭메뉴 추가
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/HomeFeed/StyledHomeFeed.jsx
Labels: refact

#35 <feat> : ModifyProfile page UI 구현
  .eslintrc.js
  src/pages/ModifyProfile/ModifyProfile.jsx
  src/pages/ModifyProfile/StyledModifyProfile.jsx
Labels: feat

#32 <feat> : 로그인이메일 페이지 UI 구현
  src/components/common/LabelInput/LabelInput.jsx
  src/components/common/LabelInput/StyledLabelInput.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/LoginEmail/StyledLoginEmail.jsx
Labels: feat

#33 <feat> : profile 공통 컴포넌트 UI 구현
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/StyledProfileInfo.jsx
  src/pages/YourProfile/StyledYourProfile.jsx
  src/pages/YourProfile/YourProfile.jsx
Labels: feat

#43 <feat> : 프로필이미지, 코멘트 입력창 UI 구현
  src/components/Comment/Comment.jsx
  src/components/Comment/StyledComment.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/StyledCommentInput.jsx
  src/components/common/ProfileImg/ProfileImg.jsx
  src/components/common/ProfileImg/StyledProfileImg.jsx
  src/pages/PostDetail/PostDetail.jsx
Labels: feat

#41 <feat> : JoinEmail 페이지 UI 구현
  src/pages/JoinEmail/JoinEmail.jsx
  src/pages/JoinEmail/StyledJoinEmail.jsx
Labels: feat

#45 PostDetail페이지 UI 구현
  src/components/Comment/StyledComment.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/PostDetail/StyledPostDetail.jsx
Labels: feat

#42 <feat> : User-Follow 공통컴포넌트 구현
  src/components/common/TabMenu/StyledTabMenu.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/components/common/UserFollow/StyledUserFollow.jsx
  src/components/common/UserFollow/UserFollow.jsx
  src/pages/FollowerList/FollowerList.jsx
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/MyProfile/MyProfile.jsx
Labels: feat

#37 <Feature> addprodut UI 구현
  src/pages/AddProduct/AddProduct.jsx
  src/pages/AddProduct/StyledAddProduct.jsx
Labels: feat

#39 <feat> : 404page UI 구현
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/StyledNotFound.jsx
Labels: feat

#48 <feat> : UploadPost 페이지 UI 구현
  src/pages/PostDetail/StyledPostDetail.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: feat

#49 <feat> : JoinProfileEdit 페이지 UI 구현
  src/components/common/ImageInput/ImageInput.jsx
  src/components/common/ImageInput/StyledImageInput.jsx
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
  src/pages/JoinProfileEdit/StyledJoinProfileEdit.jsx
Labels: feat

#52 <feat> : 판매 중인 상품 컴포넌트 완성
  src/assets/images/post-square-img-example.png
  src/components/MenuBar/MenuBar.jsx
  src/components/MenuBar/StyledMenuBar.jsx
  src/pages/YourProfile/StyledYourProfile.jsx
  src/pages/YourProfile/YourProfile.jsx
Labels: feat

#53 <feat> : search page Ui 1차 구현
  src/pages/SearchUser/SearchUser.jsx
  src/pages/SearchUser/StyledSearchUser.jsx
Labels: feat

#55 <feat> : FollowersList UI 구현
  src/components/common/UserFollow/StyledUserFollow.jsx
  src/pages/FollowerList/FollowerList.jsx
  src/pages/FollowerList/StyledFollowerList.jsx
Labels: feat

#59 <refact> : Nav 컴포넌트 수정
  src/components/Nav/Nav.jsx
  src/components/Nav/UploadNav.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/AddProduct/StyledAddProduct.jsx
  src/pages/ModifyProfile/ModifyProfile.jsx
  src/pages/ModifyProfile/StyledModifyProfile.jsx
Labels: refact

#60 <feat> : Modal 공통 컴포넌트 구현
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/StyledModal.jsx
Labels: feat

#61 <refact> : styledcomponent 수정
  src/components/common/Button/Button.jsx
  src/styles/Globalstyled.jsx
Labels: refact

#63 <Feature> : login 기능구현
  src/api/index.js
  src/components/common/Button/Button.jsx
  src/components/common/LabelInput/LabelInput.jsx
  src/context/context.js
  src/index.jsx
  src/pages/LoginEmail/LoginEmail.jsx
Labels: feat

#65 <feat> : 로그인 유효성 검사기능 추가
  src/components/common/LabelInput/LabelInput.jsx
  src/pages/LoginEmail/LoginEmail.jsx
Labels: feat

#67 <Feature> : joinEmail Page 기능구현(유효성검사)
  src/api/index.js
  src/components/common/LabelInput/LabelInput.jsx
  src/pages/JoinEmail/JoinEmail.jsx
Labels: feat

#69 <feat> : JoinProfileEdit 기능구현
  src/api/index.js
  src/components/common/ImageInput/ImageInput.jsx
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
Labels: feat

#71 <refact> : JoinEmail 기능 수정, Nav, Tapmenu UI 수정
  src/Router/Router.jsx
  src/api/index.js
  src/components/Nav/StyledNav.jsx
  src/components/common/ImageInput/ImageInput.jsx
  src/components/common/ImageInput/StyledImageInput.jsx
  src/components/common/TabMenu/StyledTabMenu.jsx
  src/context/context.js
  src/pages/JoinEmail/JoinEmail.jsx
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
  src/pages/LoginEmail/LoginEmail.jsx
Labels: refact

#74 Feature/게시글업로드기능구현 #70
  src/pages/UploadPost/UploadPost.jsx
Labels: feat

#78 <Refact> : JoinEmail 컴포넌트 비밀번호 유효성 검사 리팩토링
  src/pages/JoinEmail/JoinEmail.jsx
Labels: refact

#77 <feat> : 하단 탭 메뉴 페이지 이동 및 버튼활성화 & 글로벌스타일수정
  src/components/common/TabMenu/StyledTabMenu.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/pages/MyProfile/StyledMyProfile.jsx
  src/styles/Globalstyled.jsx
Labels: feat, refact

#81 <feat> : 유저 검색 기능 구현
  src/api/index.js
  src/components/Nav/Nav.jsx
  src/components/Nav/SearchNav.jsx
  src/pages/SearchUser/SearchUser.jsx
Labels: feat

#83 <feat> : MyProfile page UI 구현
  src/components/ProfileInfo/ProfileInfo.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/MyProfile/StyledMyProfile.jsx
  src/pages/YourProfile/StyledYourProfile.jsx
  src/pages/YourProfile/YourProfile.jsx
Labels: feat, refact

#85 <feat> : 유저 리스트 아이템 컴포넌트 제작
  src/components/Nav/SearchNav.jsx
  src/components/Nav/StyledNav.jsx
  src/components/UserListItem/StyledUserListItem.jsx
  src/components/UserListItem/UserListItem.jsx
  src/pages/SearchUser/SearchUser.jsx
  src/pages/SearchUser/StyledSearchUser.jsx
Labels: feat

#89 <Refact> : 라우터 리팩토링
  src/Router/Router.jsx
Labels: refact

#92 Feature/upload post기능구현 #75
  src/components/ImagePreview/ImagePreview.jsx
  src/components/ImagePreview/StyledImagePreview.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/UploadNav.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: feat

#91 <refact> : Nav컴포넌트 뒤로가기 버튼 기능구현
  src/components/Nav/ChatNav.jsx
  src/components/Nav/FollowHeader.jsx
  src/components/Nav/HomeNav.jsx
  src/components/Nav/MainNav.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/SearchNav.jsx
  src/components/Nav/UploadNav.jsx
Labels: refact

#95 <refact> : splash page 기능추가
  src/pages/Splash/Splash.jsx
  src/pages/Splash/StyledSplash.jsx
Labels: refact

#96 <style> : 컨벤션에 따른 수정
  src/components/Nav/Nav.jsx
Labels: style

#99 <feat> : HomeFeed 기능 구현
  src/api/index.js
  src/components/common/Button/Button.jsx
  src/components/common/PostCard/PostCard.jsx
  src/components/common/PostCard/StyledPostCard.jsx
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/HomeFeed/StyledHomeFeed.jsx
Labels: feat

#101 <feat> : 필요항목 다 채울시 버튼 활성화
  src/pages/AddProduct/AddProduct.jsx
  src/pages/AddProduct/StyledAddProduct.jsx
Labels: feat

#103 Feature/upload post게시물업로드 #93
  src/assets/images/x.svg
  src/components/Nav/Nav.jsx
  src/components/Nav/UploadNav.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: feat

#102 <feat> : Post 모달 구현
  src/components/common/Modal/MyPostModal.jsx
  src/components/common/Modal/OthersPostModal.jsx
  src/components/common/Modal/PostInnerModal.jsx
  src/components/common/Modal/StyledPostInnerModal.jsx
  src/components/common/Modal/StyledPostModal.jsx
  src/components/common/PostCard/PostCard.jsx
  src/components/common/PostCard/StyledPostCard.jsx
  src/pages/HomeFeed/HomeFeed.jsx
Labels: feat

#104 <feat> : 상품데이터 서버 전송
  src/api/index.js
  src/pages/AddProduct/AddProduct.jsx
  src/pages/AddProduct/StyledAddProduct.jsx
Labels: feat

#107 <feat> : commentInput, comment 컴포넌트 1차 기능 구현
  src/components/Comment/Comment.jsx
  src/components/Comment/StyledComment.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/StyledCommentInput.jsx
  src/pages/PostDetail/PostDetail.jsx
Labels: feat

#109 <Feature> : MyProfile, YourProfile 스타일 변경 및 데이터 받아오기
  src/Router/Router.jsx
  src/api/index.js
  src/components/MenuBar/StyledMenuBar.jsx
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/StyledProfileInfo.jsx
  src/components/UserListItem/StyledUserListItem.jsx
  src/components/UserListItem/UserListItem.jsx
  src/components/common/TabMenu/StyledTabMenu.jsx
  src/context/context.js
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/Profile/MyProfile/MyProfile.jsx
  src/pages/Profile/MyProfile/StyledMyProfile.jsx
  src/pages/Profile/YourProfile/StyledYourProfile.jsx
  src/pages/Profile/YourProfile/YourProfile.jsx
  src/pages/YourProfile/StyledYourProfile.jsx
  src/pages/YourProfile/YourProfile.jsx
  src/styles/Globalstyled.jsx
Labels: feat, refact

#110 <feat> : 상품 목록 데이터 불러오기
  src/api/index.js
  src/components/Nav/Nav.jsx
  src/components/common/Product/Product.jsx
  src/components/common/Product/ProductWrapp.jsx
  src/components/common/Product/StyledProduct.jsx
  src/components/common/Product/StyledProductWrapp.jsx
  src/pages/AddProduct/AddProduct.jsx
Labels: feat, refact

#112 <feat> : 검색 페이지 무한 스크롤 구현
  src/pages/SearchUser/SearchUser.jsx
Labels: feat

#115 <Refact> : 홈피드 리팩토링
  src/components/common/PostCard/PostCard.jsx
  src/components/common/PostCard/StyledPostCard.jsx
  src/pages/HomeFeed/HomeFeed.jsx
Labels: refact

#117 <feat> : 상품리스트 메인+이너 모달 추가
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/ProductInnerModal.jsx
  src/components/common/Modal/StyledModal.jsx
  src/components/common/Product/Product.jsx
  src/components/common/Product/ProductWrapp.jsx
  src/components/common/Product/StyledProduct.jsx
  src/components/common/Product/StyledProductWrapp.jsx
  src/pages/AddProduct/StyledAddProduct.jsx
Labels: feat

#118 <feat> : 좋아요 버튼 기능 구현
  src/assets/images/heart.svg
  src/components/common/Button/LikeButton.jsx
  src/components/common/PostCard/PostCard.jsx
Labels: feat

#119 <refact> : UserProfile 병합 및 이용자 게시물 데이터 받아오기 구현
  src/Router/Router.jsx
  src/api/index.js
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/UserListItem/UserListItem.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/pages/Profile/MyProfile/MyProfile.jsx
  src/pages/Profile/MyProfile/StyledMyProfile.jsx
  src/pages/Profile/UserProfile/StyledUserProfile.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
  src/pages/Profile/YourProfile/StyledYourProfile.jsx
  src/pages/Profile/YourProfile/YourProfile.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: refact

#120 <feat> : PostDetail 게시물, 댓글, 모달 기능구현
  .eslintrc.js
  src/Router/Router.jsx
  src/components/Comment/Comment.jsx
  src/components/Comment/StyledComment.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/common/Modal/CommentModal.jsx
  src/components/common/Modal/StyledCommentModal.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/PostDetail/StyledPostDetail.jsx
Labels: feat

#123 <feat> : 상품 삭제 기능 추가
  src/components/common/Modal/ProductInnerModal.jsx
  src/components/common/Modal/ProductModal.jsx
  src/components/common/Modal/StyledProductModal.jsx
  src/components/common/Product/Product.jsx
  src/components/common/Product/ProductWrapp.jsx
  src/components/common/Product/StyledProduct.jsx
Labels: feat

#124 <Refact> : 모달 컴포넌트 리팩토링
  src/components/common/Modals/InnerModal.jsx
  src/components/common/Modals/Modal.jsx
  src/components/common/Modals/ModalBtn.jsx
  src/components/common/Modals/StyledInnerModal.jsx
  src/components/common/Modals/StyledModal.jsx
  src/components/common/PostCard/PostCard.jsx
  src/hooks/useModal.jsx
Labels: refact

#127 <feat> : 프로필 페이지 모달 구현
  src/components/Nav/HomeNav.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: feat

#129 <Refact> : NotFound 뒤로가기 버튼 기능 추가
  src/pages/NotFound/NotFound.jsx
Labels: refact

#130 <refact> : 상품 모달 커스텀 훅으로 리팩토링
  src/components/common/Modal/ProductInnerModal.jsx
  src/components/common/Modal/ProductModal.jsx
  src/components/common/Modals/InnerModal.jsx
  src/components/common/Modals/ModalBtn.jsx
  src/components/common/PostCard/PostCard.jsx
  src/components/common/Product/Product.jsx
  src/components/common/Product/ProductWrapp.jsx
  src/hooks/useModal.jsx
Labels: refact

#131 <feat> : UserProfile_Follow Button 기능추가
  src/api/index.js
  src/components/Nav/HomeNav.jsx
  src/components/ProfileInfo/MyProfileBtnWrapp.jsx
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/UserProfileBtnWrapp.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Button/FollowButton.jsx
  src/components/common/Button/StyledBtn.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: refact

#134 <refact> : UseProfile_Post 리스트형, 앨범형 선택 버튼 기능 구현, Product 컴포넌트 추가 및 스타일 수정
  src/api/index.js
  src/components/MenuBar/MenuBar.jsx
  src/components/MenuBar/StyledMenuBar.jsx
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/StyledProfileInfo.jsx
  src/components/common/PostAlbum/PostAlbum.jsx
  src/components/common/Product/ProductWrapp.jsx
  src/components/common/Product/StyledProductWrapp.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/Profile/UserProfile/StyledUserProfile.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: refact

#133 Feature/uploadpost이미지3장미리보기구현
  src/api/index.js
  src/components/Comment/StyledComment.jsx
  src/components/CommentInput/StyledCommentInput.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/PostDetail/StyledPostDetail.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: feat

#135 <feat> : 상품 수정 버튼 클릭시 수정페이지로 이동
  src/Router/Router.jsx
  src/components/common/Product/Product.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/UpdateProduct/UpdateProduct.jsx
Labels: refact

#137 Feature/edit post페이지기능구현 #136
  src/Router/Router.jsx
  src/pages/EditPost/EditPost.jsx
  src/pages/EditPost/StyledEditPost.jsx
Labels: feat
