Repository TEAM-HI25/nonamarket, pull requests merged in 2023-01, with the labels that each got.

#140 <refact> : ChatList & ChatUserList UI 추가
  src/Router/Router.jsx
  src/components/UserListItem/ChatUserList.jsx
  src/components/UserListItem/StyledUserListItem.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/pages/ChatList/ChatList.jsx
  src/pages/ChatList/StyledChatList.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/Profile/YourProfile/StyledYourProfile.jsx
  src/pages/Profile/YourProfile/YourProfile.jsx
  src/pages/SearchUser/StyledSearchUser.jsx
Labels: refact

#141 <refact> : FollowerList Ui 수정 및 Link 연결 기능구현
  src/Router/Router.jsx
  src/components/Nav/FollowHeader.jsx
  src/components/Nav/Nav.jsx
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/StyledProfileInfo.jsx
  src/components/UserListItem/UserFollow/StyledUserFollow.jsx
  src/components/UserListItem/UserFollow/UserFollow.jsx
  src/components/common/UserFollow/StyledUserFollow.jsx
  src/components/common/UserFollow/UserFollow.jsx
  src/pages/Follow/FollowCard.jsx
  src/pages/Follow/FollowerList.jsx
  src/pages/Follow/FollowingList.jsx
  src/pages/Follow/StyledFollowerList.jsx
  src/pages/FollowerList/StyledFollowerList.jsx
  src/pages/FollowingList/FollowingList.jsx
Labels: refact

#146 <feat> : followingList data 받아오기
  src/components/UserListItem/UserFollow/UserFollow.jsx
  src/pages/Follow/FollowingList.jsx
Labels: feat

#147 <feat> : Loading 컴포넌트 구현
  src/assets/images/loading.gif
  src/components/Loading/Loading.jsx
  src/components/Loading/StyledLoading.jsx
  src/pages/HomeFeed/HomeFeed.jsx
Labels: feat

#151 <Style> : 회원가입 버튼 문구 수정
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
Labels: style

#152 <Refact> : uploadpost 이미지 UI 리팩토링
  src/pages/EditPost/EditPost.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: refact

#154 <Refact> : 포스트카드 프로필 경로 수정
  src/components/common/PostCard/PostCard.jsx
Labels: refact

#158 <feat> : 상품 웹사이트 링크로 이동 구현
  src/components/common/Product/Product.jsx
  src/components/common/Product/StyledProductWrapp.jsx
Labels: feat

#157 <Refact> : 홈피드 가운데 정렬 리팩토링
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/HomeFeed/StyledHomeFeed.jsx
Labels: refact

#161 <refact> : Comment모달 리팩토링
  src/components/Comment/Comment.jsx
  src/components/common/Modal/CommentModal.jsx
  src/components/common/Modal/MyPostModal.jsx
  src/components/common/Modal/OthersPostModal.jsx
  src/components/common/Modal/PostInnerModal.jsx
  src/components/common/Modal/StyledCommentModal.jsx
  src/components/common/Modal/StyledPostInnerModal.jsx
  src/components/common/Modal/StyledPostModal.jsx
  src/components/common/Modal/StyledProductModal.jsx
  src/components/common/Modals/InnerModal.jsx
  src/components/common/Modals/StyledModal.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
Labels: refact

#163 <feat> : 소셜 로그인 페이지 모달 애니메이션 추가
  src/pages/Login/StyledLogin.jsx
Labels: feat

#165 <refact> : UserProfile_PostCardAlbumtype 이미지 받아오기 수정
  src/components/common/PostAlbum/PostAlbum.jsx
  src/pages/Profile/UserProfile/StyledUserProfile.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: refact

#168 <refact> : 댓글 삭제기능 리팩토링
  src/components/Comment/Comment.jsx
  src/pages/PostDetail/PostDetail.jsx
Labels: refact

#170 <feat> : postcard 이미지 렌더링 기능구현
  src/components/common/PostCard/PostCard.jsx
  src/components/common/PostCard/StyledPostCard.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: feat

#171 <refact> : 무료나눔 기능 추가
  src/components/common/Product/Product.jsx
  src/components/common/Product/ProductWrapp.jsx
  src/pages/AddProduct/AddProduct.jsx
Labels: fix, refact

#173 <refact> : 탭메뉴 기능 수정
  src/components/common/TabMenu/TabMenu.jsx
Labels: fix, refact

#175 <feat> : ModifyProfile 기능 구현 (프로필 수정)
  src/api/index.js
  src/pages/Follow/FollowerList.jsx
  src/pages/Follow/FollowingList.jsx
  src/pages/ModifyProfile/ModifyProfile.jsx
  src/pages/ModifyProfile/StyledModifyProfile.jsx
  src/pages/UpdateProduct/UpdateProduct.jsx
Labels: feat

#178 <refact> : MainNav 컴포넌트 로고이미지 교체
  src/assets/images/logo-txt.svg
  src/components/Nav/MainNav.jsx
Labels: refact

#179 <refact>:Splash 애니메이션 추가
  src/pages/Splash/Splash.jsx
  src/pages/Splash/StyledSplash.jsx
Labels: refact

#180 <style> : css수정 및 주석, console 삭제
  src/api/index.js
  src/components/ProfileInfo/StyledProfileInfo.jsx
  src/components/common/Button/FollowButton.jsx
  src/components/common/PostCard/StyledPostCard.jsx
  src/components/common/ProfileImg/StyledProfileImg.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
  src/pages/SearchUser/StyledSearchUser.jsx
  src/styles/Globalstyled.jsx
Labels: style

#181 <refact> : 스크롤바 스타일링 추가
  src/components/common/Product/StyledProductWrapp.jsx
Labels: style

#182 <refact> : comment 리스트 key값 추가
  src/pages/PostDetail/PostDetail.jsx
Labels: refact

#183 <fix> : 에러코드 수정
  src/components/common/PostCard/PostCard.jsx
  src/components/common/PostCard/StyledPostCard.jsx
  src/pages/Follow/FollowerList.jsx
  src/pages/Follow/FollowingList.jsx
  src/pages/PostDetail/PostDetail.jsx
Labels: fix

#184 <refact> : Follower, Following List에서 follow 상태에 따른 버튼변경 기능 추가
  src/components/UserListItem/UserFollow/UserFollow.jsx
  src/pages/Follow/FollowerList.jsx
  src/pages/Follow/FollowingList.jsx
  src/pages/Profile/UserProfile/StyledUserProfile.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: refact

#186 <refact> : 팔로우 리스트에서 팔로우/언팔로우 기능 추가
  src/components/UserListItem/UserFollow/UserFollow.jsx
  src/pages/Follow/FollowerList.jsx
  src/pages/Follow/FollowingList.jsx
  src/pages/Profile/UserProfile/StyledUserProfile.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: refact

#187 <refact> : editpost 이미지 업로드 리팩토링
  src/pages/EditPost/EditPost.jsx
  src/pages/EditPost/StyledEditPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: refact

#189 <refact> : API파일 구조 변경
  src/api/commentAPI.js
  src/api/imageAPI.js
  src/api/likeAPI.js
  src/api/postAPI.js
  src/api/productAPI.js
  src/api/profileAPI.js
  src/api/searchAPI.js
  src/api/userAPI.js
  src/utills/baseUrl.js
Labels: refact

#191 <refact> : 상품 관련 API 코드 파일 분리
  src/api/productAPI.js
  src/components/common/Modals/InnerModal.jsx
  src/components/common/Product/ProductWrapp.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/UpdateProduct/UpdateProduct.jsx
Labels: refact

#194 <refact> : 정규표현식 utils 폴더 안 파일 분리
  src/pages/AddProduct/AddProduct.jsx
  src/pages/JoinEmail/JoinEmail.jsx
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/UpdateProduct/UpdateProduct.jsx
  src/utils/regex.js
Labels: refact

#197 <Refact> : 로그인 및 회원가입 API 분리
  src/api/imageAPI.js
  src/api/index.js
  src/api/userAPI.js
  src/pages/JoinEmail/JoinEmail.jsx
  src/pages/JoinProfileEdit/JoinProfileEdit.jsx
  src/pages/LoginEmail/LoginEmail.jsx
Labels: refact
