Repository TEAM-HI25/nonamarket, pull requests merged in 2023-02, with the labels that each got.

#198 [Refact] : UserprofilePage api 분리 (FollowerList, FollwoingList, Profile, Post, ModifyProfile )
  src/api/index.js
  src/api/postAPI.js
  src/api/profileAPI.js
  src/api/userAPI.js
  src/pages/Follow/FollowerList.jsx
  src/pages/Follow/FollowingList.jsx
  src/pages/ModifyProfile/ModifyProfile.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: refact

#200 <refact> : 홈피드 API 분리
  src/api/index.js
  src/api/postAPI.js
  src/pages/HomeFeed/HomeFeed.jsx
Labels: refact

#202 <Refact> : 검색 페이지 API 분리
  src/api/index.js
  src/api/searchAPI.js
  src/pages/SearchUser/SearchUser.jsx
Labels: refact

#205 <Refact> : 게시글 삭제 및 신고 모달 api분리
  src/api/postAPI.js
  src/components/common/Modals/InnerModal.jsx
Labels: refact

#211 <refact>: UploadPostPage API 분리
  src/api/postAPI.js
  src/pages/UploadPost/UploadPost.jsx
  src/pages/UploadPost/UploadPostRefact.jsx
Labels: refact

#208 <fix> : handleSubmit function & 정규표현식_ACCOUNT_CHECK 코드 수정
  src/pages/ModifyProfile/ModifyProfile.jsx
Labels: fix

#213 <refact> : 상품 수정&등록 중복 코드 정리
  src/Router/Router.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/EditProduct/EditProduct.jsx
  src/pages/UpdateProduct/UpdateProduct.jsx
Labels: refact

#217 <refact> : ProductForm 컴포넌트 생성
  src/components/ProductForm/ProductForm.jsx
  src/components/ProductForm/StyledProductForm.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/EditProduct/EditProduct.jsx
Labels: refact

#218 Refact/edit post리팩토링
  src/api/postAPI.js
  src/pages/EditPost/EditPost copy.jsx
  src/pages/EditPost/EditPost.jsx
  src/pages/UploadPost/StyledUploadPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: refact

#220 <refact>: PostDetail Page API 분리
  src/api/postAPI.js
  src/pages/EditPost/EditPost copy.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: refact

#222 <refact>: 댓글 삭제/신고 모달 API 분리
  src/api/commentAPI.js
  src/components/Comment/Comment.jsx
  src/components/common/Modals/InnerModal.jsx
Labels: refact

#224 <Refact> : UserProfile 컴포넌트의 가독성을 높이기 위한 리펙토링
  src/pages/Profile/UserProfile/StyledUserProfile.jsx
  src/pages/Profile/UserProfile/UserProfile.jsx
Labels: refact

#225 <refact> : 채팅리스트페이지 더미데이터 추가
  src/Router/Router.jsx
  src/components/UserListItem/ChatUserList.jsx
  src/pages/ChatList/ChatList.jsx
  src/pages/ChatList/chatData.json
Labels: refact

#227 <feat> : 개별 채팅 페이지 UI 완성
  src/components/Nav/ChatNav.jsx
  src/components/Nav/Nav.jsx
  src/components/UserListItem/ChatUserList.jsx
  src/components/UserListItem/StyledUserListItem.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/ChatRoom/StyledChatRoom.jsx
Labels: feat

#230 <Feat>: 이미지 압축 기능 추가
  package-lock.json
  package.json
  src/api/commentAPI.js
  src/api/postAPI.js
  src/pages/UploadPost/UploadPost.jsx
Labels: feat

#232 <refact>: uploadpost/editpost 페이지 중복코드 추출
  src/components/PostForm/PostForm.jsx
  src/components/PostForm/StyledPostForm.jsx
  src/pages/EditPost/EditPost.jsx
  src/pages/EditPost/StyledEditPost.jsx
  src/pages/UploadPost/UploadPost.jsx
Labels: refact

#233 <docs>: console.log 삭제
  src/components/PostForm/PostForm.jsx
Labels: docs
